#!/usr/bin/env bash




if [-z "$1"]; then
    echo "Need to specify the paramater/ bucket name";
    exit 1
fi

echo "== Delete bucket"

BUCKET_NAME=$1
aws s3api delete-bucket \
--bucket $BUCKET_NAME 
