#!/usr/bin/env bash

echo "== Put object"

if [ -z "$1"]; then
    echo "There needs to be a bucket name eg .. /bucket my-bucket-name"
    exit 1
fi

if [ -z "$2"]; then
    echo "There needs to be a filename"
    exit
fi

BUCKET_NAME=$1
FILENAME=$2

KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $KEY
