#!/usr/bin/env bash
echo "== Sync"

# Exit if any error occurs
set -e

if [ -z "$1"]; then
    echo "There needs to be a bucket name eg .. /bucket my-bucket-name"
    exit 1
fi
if [ -z "$2"]; then
    echo "There needs to be a filename prefix "
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2


# where we will store these random files
OUT="/tmp/s3-bash-scripts"


# remove folder if it already exist
rm -r $OUT

# create output folder - no error if existing, make parent directories as needed
mkdir -p $OUT

NUM_FILES=$((RANDOM % 6 + 5))

for((i = 1; i<= $NUM_FILES; i++)); do
    #Generate the files
    FILENAME="$OUT/${FILENAME_PREFIX}_$i.txt"
    
    #Generate random data and write to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUT

aws s3 sync $OUT s3://$BUCKET_NAME/files

